name: desktop_wallpaper

repository: https://github.com/KRTirtho/desktop_wallpaper

packages:
  - packages/**

scripts:
  analyze:
    exec: flutter analyze .
    description: Analyze a specific package in this project.

  check-format:
    exec: dart format --set-exit-if-changed .
    description: Check the format of a specific package in this project.

  format:
    exec: dart format .
    description: Format a specific package in this project.

  version:
    description: Updates version numbers in all build files
    run: bash scripts/version.sh

  build:
    run: melos run build:apple && melos run build:other
    description: Build all native libraries for the project.

  build:apple:
    run: bash scripts/build-apple.sh
    description: Build the XCFramework for macOS.

  build:other:
    run: bash scripts/build-other.sh
    description: Build the .tar.gz for all other platforms.

  copylib:linux:
    run: |
      CURR_VERSION=v`awk '/^version: /{print $2}' packages/desktop_wallpaper/pubspec.yaml`
      cp platform-build/other.tar.gz packages/desktop_wallpaper/linux/$CURR_VERSION.tar.gz
  copylib:windows:
    run: |
      CURR_VERSION=v`awk '/^version: /{print $2}' packages/desktop_wallpaper/pubspec.yaml`
      cp platform-build/other.tar.gz packages/desktop_wallpaper/windows/$CURR_VERSION.tar.gz
  copylib:macos:
    run: |
      CURR_VERSION=v`awk '/^version: /{print $2}' packages/desktop_wallpaper/pubspec.yaml`
      cp platform-build/MetadataGod.xcframework.zip packages/desktop_wallpaper/macos/Frameworks/$CURR_VERSION.zip

  test:
    run: melos exec -c 1 --fail-fast -- "flutter test test"
    description: Run Flutter tests for a specific package in this project.
    select-package:
      flutter: true
      dir-exists: test
