name: desktop_wallpaper_example
description: Demonstrates how to use the desktop_wallpaper plugin.

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  desktop_wallpaper:
    path: ../

  cupertino_icons: ^1.0.2
  file_picker: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
