name: desktop_wallpaper
description: Get and set desktop wallpaper on Windows, Linux, and macOS.
version: 0.1.0
homepage: https://github.com/KRTirtho/desktop_wallpaper

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.11.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.2
  flutter_rust_bridge: ^1.78.0
  meta: ^1.9.1

dev_dependencies:
  ffigen: ">=8.0.2 <10.0.0"
  lints: ^2.1.1
  test: ^1.24.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  plugin:
    platforms:
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
