// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.78.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';
import 'bridge_generated.dart';
export 'bridge_generated.dart';

class DesktopWallpaperPlatform extends FlutterRustBridgeBase<DesktopWallpaperWire> with FlutterRustBridgeSetupMixin {
  DesktopWallpaperPlatform(FutureOr<WasmModule> dylib) : super(DesktopWallpaperWire(dylib)) {
    setupMixinConstructor();
  }
  Future<void> setup() => inner.init;

// Section: api2wire

  @protected
  String api2wire_String(String raw) {
    return raw;
  }

  @protected
  Uint8List api2wire_uint_8_list(Uint8List raw) {
    return raw;
  }

// Section: finalizer
}

// Section: WASM wire module

@JS('wasm_bindgen')
external DesktopWallpaperWasmModule get wasmModule;

@JS()
@anonymous
class DesktopWallpaperWasmModule implements WasmModule {
  external Object /* Promise */ call([String? moduleName]);
  external DesktopWallpaperWasmModule bind(dynamic thisArg, String moduleName);
  external dynamic /* void */ wire_get_wallpaper(NativePortType port_);

  external dynamic /* void */ wire_set_wallpaper(NativePortType port_, String path);

  external dynamic /* void */ wire_set_mode(NativePortType port_, int mode);
}

// Section: WASM wire connector

class DesktopWallpaperWire extends FlutterRustBridgeWasmWireBase<DesktopWallpaperWasmModule> {
  DesktopWallpaperWire(FutureOr<WasmModule> module) : super(WasmModule.cast<DesktopWallpaperWasmModule>(module));

  void wire_get_wallpaper(NativePortType port_) => wasmModule.wire_get_wallpaper(port_);

  void wire_set_wallpaper(NativePortType port_, String path) => wasmModule.wire_set_wallpaper(port_, path);

  void wire_set_mode(NativePortType port_, int mode) => wasmModule.wire_set_mode(port_, mode);
}
