[package]
name = "desktop_wallpaper"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.78.*"

[dependencies]
flutter_rust_bridge = "1.79.*"
wallpaper = "3.2.0"
